### ISSUE TITLE
UFOZ support?

### ISSUE THREAD

**Issue by jenskutilek** [justvanrossum/fontgoggles#147]
Should UFOZ work?

I tried to load a .ufoz file in FontGoggles, but only get a traceback:

```
Traceback (most recent call last):
  File "fontgoggles/mac/mainWindow.pyc", line 497, in _loadFont
  File "fontgoggles/project.pyc", line 139, in load
  File "fontgoggles/project.pyc", line 172, in loadFont
  File "fontgoggles/font/ufoFont.pyc", line 57, in load
  File "fontgoggles/font/ufoFont.pyc", line 358, in __init__
  File "fontgoggles/font/ufoFont.pyc", line 458, in getGlyphModTimes
  File "fs/wrapfs.pyc", line 380, in getsyspath
  File "fs/wrapfs.pyc", line 380, in getsyspath
  File "fs/base.pyc", line 786, in getsyspath
fs.errors.NoSysPath: path '/TheUFO.ufo/glyphs' does not map to the local filesystem
```

**Comment by justvanrossum** [comment]
Should, but doesn't! Thanks for the report.

The culprit is here:
https://github.com/justvanrossum/fontgoggles/blob/255d430f4daeee61223b17dba526e72094f07a1e/Lib/fontgoggles/font/ufoFont.py#L458

I don't see a trivial fix, so this will require some more time and research.

**Comment by justvanrossum** [comment]
Was easier than I thought! Sorry it took so long.

**Comment by justvanrossum** [comment]
Or actually, my fix is not complete: it doesn't work for a designspace using ufoz sources.
