### ISSUE TITLE
Follow symbolic links

### ISSUE THREAD

**Issue by justvanrossum** [justvanrossum/fontgoggles#350]
Dropping a symlink to a .designspace file currently doesn't work, as FontGoggles will look for the sources in the folder of the symlink. It should probably resolve the symlinks before reading.

**Comment by justvanrossum** [comment]
```
Traceback (most recent call last):
  File "/Users/just/code/git/fontgoggles/Lib/fontgoggles/mac/mainWindow.py", line 508, in _loadFont
    await fontItemInfo.load(outputWriter=fontItem.writeCompileOutput)
  File "/Users/just/code/git/fontgoggles/Lib/fontgoggles/project.py", line 139, in load
    await self._fontLoader.loadFont(self.fontKey, outputWriter)
  File "/Users/just/code/git/fontgoggles/Lib/fontgoggles/project.py", line 172, in loadFont
    await font.load(outputWriter)
  File "/Users/just/code/git/fontgoggles/Lib/fontgoggles/font/dsFont.py", line 74, in load
    reader = UFOReader(source.path, validate=False)
  File "/Users/just/code/git/fontgoggles/venv39/lib/python3.9/site-packages/fontTools/ufoLib/__init__.py", line 213, in __init__
    structure = _sniffFileStructure(path)
  File "/Users/just/code/git/fontgoggles/venv39/lib/python3.9/site-packages/fontTools/ufoLib/__init__.py", line 1751, in _sniffFileStructure
    raise UFOLibError("No such file or directory: '%s'" % ufo_path)
fontTools.ufoLib.errors.UFOLibError: No such file or directory: '/Users/just/JobJob/ATypI 2023/Fontra ATypI Demos/GrtskZetta-Thin.ufo'
```
