### ISSUE TITLE
pytz.exceptions.UnknownTimeZoneError: 'GMT'

### ISSUE THREAD

**Issue by typoman** [justvanrossum/fontgoggles#376]
I saved a UFO file in another program and on update font goggles choked on the refreshing and I got this error:

```
Traceback (most recent call last):
  File "fontgoggles/compile/workServer.pyc", line 32, in workServer
  File "importlib/__init__.pyc", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "fontgoggles/compile/ufoCompiler.pyc", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "fontTools/ufoLib/__init__.pyc", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "fs/base.pyc", line 28, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "fs/time.pyc", line 14, in <module>
  File "pytz/__init__.pyc", line 181, in timezone
pytz.exceptions.UnknownTimeZoneError: 'GMT'
CompilerError('fontgoggles.compile.ufoCompiler.compileUFOToPath')
```

I can't reproduce it after I restarted fontGoggles though :)

**Comment by anthrotype** [comment]
very strange.. it looks like a bug in pyfilesystem2 (`fs` module).

**Comment by anthrotype** [comment]
in theory pytz should no longer be a dependency of pyfilesystem2, so i'm surprised it gets called there.
https://github.com/PyFilesystem/pyfilesystem2/issues/516
which version of `fs` module have you got installed?

**Comment by justvanrossum** [comment]
FontGoggles doesn't pin `fs`, so I guess it is the one that was current during the last FontGoggles release.
